# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05735195cdad52c8af906b8b3e1a224fb8acf78d7d959c4dcfae941522e00b3283c9d0bfcebf1409d5107bd7748fe2d93e8956f6e838d789f6895584e1427be2

test:
  secret_key_base: 7597224ef131e9093d5bfeec1274ac622e24afe811288a179d3b85c56be81a81ecb1191cd3348db10e4f273c55fbcf67f22b081a24760c6ad9cca1a419c9c9d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
